
name: CI/CD

on:
  push:
    branches:
      - api
    paths:
      - requirements.txt
      - zappa_settings.json
      - app.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: "pip"

    - name: Set up the virtual environment and install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install zappa  # Corrigido: Instalar Zappa explicitamente

    - name: Deploy to AWS with Zappa
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
      run: |
        # Install the AWS CLI
        pip install awscli
        
        # Configure the AWS CLI
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION
        
        # Activate the virtual environment
        source env/bin/activate
        
        # Deploy or update with Zappa
        zappa update dev
